### ISSUE TITLE
Vimwiki Diary

### ISSUE THREAD

**Issue by folofjc** [michal-h21/vimwiki-sync#12]
Since the command to add is simply `git -C " . g:zettel_dir . " add . `, it will only add files at the top level of the vimwiki. Vimwiki diaries by default live in the `diary/` folder at the top level, and therefore do not get added. Would be great if this could be incorporated. It is an easy fix (probably including testing if a folder at `diary_rel_path` exists, then add everything in it. I can submit a PR if you want.

**Comment by michal-h21** [comment]
Nice idea! If you want to make a PR, I would be glad.

**Comment by folofjc** [comment]
So I am not so sure that it doesn't work:/ It didn't at first, but then I opened it again and it looks like it did add them, but I don't know why, since they are not at the top level of `g:zettel_dir`. Can you check and see if it adds things in the `diary/` directory?

**Comment by michal-h21** [comment]
I've just tried it, and it seems that the things in subdirectories are added.

**Comment by folofjc** [comment]
Okay, then I'll close this. It was not working at first, I tried opening and closing vim and vimwiki multiple times and it did not add them. Based upon [this link](https://stackoverflow.com/a/26039014/2521096) it seems to me like it _should not_ add them. So not sure why it does, but I am glad that it does!
