### ISSUE TITLE
job_start is not available on neovim

### ISSUE THREAD

**Issue by chipsenkbeil** [michal-h21/vimwiki-sync#2]
I'm assuming this plugin is designed for vim and not neovim? 

Neovim job control has [`jobstart`](https://neovim.io/doc/user/eval.html#jobstart()) and I've seen plugins that embed [async.vim](https://github.com/prabirshrestha/async.vim) to provide a consistent API, although from skimming the plugin it looks like you aren't doing anything after spawning the jobs, so maybe just an alias to starting a job that supports either would work?

I may fiddle with this to see if I can get a working solution.

**Comment by michal-h21** [comment]
@chipsenkbeil yes, I only use Vim, so I don't know much about Neovim's job handling. But I am definitely interested in Neovim support, it would be great to add it.

**Comment by chipsenkbeil** [comment]
@michal-h21, I'm just now fiddling with vimwiki (and your vim-zettel plugin). I'll take a crack at this soon.

**Comment by Chickensoupwithrice** [comment]
Hey I made a pull request for this issue, but I'm no vimscript expert. 
I'm not sure if the async nature of jobstart (as I deduce it to be) will interfere with the commands. I may be wrong.

Thanks a ton for creating vim-zettel and this plugin, I use them often! :)

**Comment by michal-h21** [comment]
@Chickensoupwithrice I've incorporated your code, thank you. And thanks for your kind words!
