### ISSUE TITLE
Shell is assumed to be bash

### ISSUE THREAD

**Issue by rkmiec** [michal-h21/vimwiki-sync#6]
When shell variable is not set to bash (fish in my case), the commit log message leaves just the `date`
string without expanding it.

**Comment by michal-h21** [comment]
Thanks for the report. I've fixed it in ddf0677. The internal `strftime` function is used for the date message, instead of a shell call to the date command.

**Comment by rkmiec** [comment]
It works great now. Thanks for the quick update.
