### ISSUE TITLE
Will it only make a commit or commit and push? 

### ISSUE THREAD

**Issue by usmanity** [michal-h21/vimwiki-sync#7]
The commit message says: 
```
Auto commit + push.
```
But I checked my github history and no commits are pushed. Is this by design or am I misunderstanding the commit message?

**Comment by michal-h21** [comment]
It definitely isn't by design, changes should be pushed. I've updated the plugin to use a different way how to run Git. Did that help? If it doesn't help, could you create a log file using `vim -Verror.txt path/to/wikiindex`? It should contain some error messages in the case of fail.

**Comment by usmanity** [comment]
Thanks for the quick response, here's what I got from the error 
```
Executing VimLeave Autocommands for "*"
autocommand call <sid>git_action("git -C " . g:zettel_dir . " push origin master")

:!git -C /Users/muhammad/z/ push origin master

Executing command: "git -C /Users/muhammad/z/ push origin master"

error: src refspec master does not match any
error: failed to push some refs to 'github.com:usmanity/zettelkasten.git'

shell returned 1
```

Looks like the sync plugin is trying to push to `master` branch but my branch is called `main`. 

Maybe if the push and pull were done against the current branch e.g. `git push origin HEAD`, that might work?

**Comment by michal-h21** [comment]
@usmanity you are right, I've assumed the `master` branch, which is not a good idea. I've changed that to `HEAD` in the latest commit. It is also possible to manually select the branch name using new variable:

      let g:vimwiki_sync_branch = "main"

**Comment by usmanity** [comment]
great! Thank you so much!
